### ISSUE TITLE
Is this URP compatible?

### ISSUE THREAD

**Issue by adelriosantiago** [tzax/FastFakeSkin#1]
Is this URP compatible?

When converting the project into URP the skin materials are not converted and look like this:

![image](https://user-images.githubusercontent.com/5462382/188255045-e722c661-31bb-491a-9142-164b62ab47cd.png)

Any idea how to fix this?

**Comment by tzax** [comment]
The shader only works with the built-in unity rendering pipeline (aka the Standard one). The converter doesn't work on custom shaders afaik.

**Comment by tzax** [comment]
Closing. Unfortunately porting to urp would take a while and would be outside the scope of the current shader; it would be more a feature, rather and fixing an issue.
